#!/bin/sh
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$STAGED_FILES" ] && exit 0

# For each staged file prettier, eslint and tests
# Opted for less verbose error messages when committing, run the npm scripts manually for more verbose output to debug

# Prettify all selected STAGED_files
(echo "$STAGED_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write &> /dev/null ) || (echo "Prettier failed!" && exit 1)

# Lint all selected STAGED_files
(echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix --ext .ts &> /dev/null ) || (echo "ESLint failed!" && exit 1)

# Add back the modified/prettified STAGED_files to staging
echo "$STAGED_FILES" | xargs git add

# Runs all tests
(npm run test &> /dev/null) || (echo "Tests failed!" && exit 1)

exit 0