name: Pull requests
run-name: Runninf lint, test and build

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    lint-test-build-pr:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Copy env file
              run: |
                  touch .env
                  echo "${{ secrets.TEST }}" > .env
            - name: Install dependencies
              run: npm install
            - name: Lint
              run: npm run lint:fix
            - name: Test
              run: npm run test
            - name: Build
              run: npm run build --if-present
